-- 004_user_files_created_by.sql
-- Phase 2.5: distinguish files uploaded by the user from files generated by
-- the assistant. Phase 3 will populate `'assistant'`; for now everything is
-- `'user'`.

ALTER TABLE user_files
    ADD COLUMN IF NOT EXISTS created_by text NOT NULL DEFAULT 'user'
        CHECK (created_by IN ('user', 'assistant'));

CREATE INDEX IF NOT EXISTS idx_user_files_user_creator
    ON user_files (user_id, created_by, created_at DESC);
